<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'items search');
?>

<h2><?php echo $translate('Advanced item search'); ?></h2>
<form id="advanced-search" method="get" action="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>">

<?php echo $this->partial(
    'common/advanced-search',
    ['query' => $this->params()->fromQuery(), 'resourceType' => 'item']
); ?>

<!--
<div class="advanced-search-content">
  <div aria-labelledby="by-value-label" class="field removable multi-value" id="property-queries" role="group">
  <div class="field-meta">
	<span class="label" id="by-value-label">Search by value</span>
  </div>
  <div class="inputs">
	<div class="value">
	<select aria-label="Property" class="query-property" name="property[0][property]">
	  <option value="">[Any Property]</option>
	  <option value="1" selected="selected">Title</option>
	  <option value="2">Author (name)</option>
	  <option value="77">Recipient (name)</option>
	  <option value="13">Mentioned (name)</option>
	</select> 
	<select aria-label="Query type" class="query-type" name="property[0][type]">
	  <option value="eq">is exactly</option>
	  <option value="neq">is not exactly</option>
	  <option value="in" selected="selected">contains</option>
	  <option value="nin">does not contain</option>
	  <option value="ex">has any value</option>
	  <option value="nex">has no values</option>
	</select> 
	<input aria-label="Query text" class="query-text" name="property[0][text]" type="text" value=""> 
	<select class="joiner" name="property[0][joiner]">
	  <option value="and">AND</option>
	  <option value="or">OR</option>
	</select> 
	</div>
	<button class="o-icon-delete remove-value button" type="button">Remove value</button>
	<a class="add-value button" href="#">Add new value</a>
	</div>
  </div>
</div>
-->

<div id="page-actions">
    <input type="submit" name="submit" value="<?php echo $this->escapeHtml($translate('Search')); ?>">
</div>
</form>
