<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Crimson+Text:400,400italic,700,700italic|Roboto:100,300,400|Oswald:100,300,400|Bitter:700');
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/custom.css'));
$this->headScript()->prependFile($this->assetUrl('js/centerrow.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <?php echo $userBar; ?>
        <div id="wrap">
	    <div id="utility">Sites: <a href="http://edisondigital.rutgers.edu">Digital Edition</a> | <a href="http://edison.rutgers.edu">Edison Papers</a></div>
            <header>
                <a href="<?php echo $site->url(); ?>" class="site-title"></a>
	    </header>
	    <div id="sub-title">
                <?php if ($this->themeSetting('logo')): ?>
		<img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo">
		<!--<img src="https://edison.rutgers.edu/webimages/nhprc-taep2.png" id="logo-nhprc" title="NHPRC">-->
		</a>
                <?php else: ?>
                <!--<a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>-->
                <?php endif; ?>
                <div id="search-container">
                    <?php echo $this->partial('common/search-form'); ?>
                    <button type="button" class="search-toggle" title="Toggle search"></button>
                </div>
	    </div>
	    <header style="background-color:#fff;margin-top:10px;">
                <nav>
                <?php
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'maxDepth' => $this->themeSetting('nav_depth') - 1
                ]);
                ?>
                </nav>
            </header>

            <div id="content" role="main">
                <?php echo $this->content; ?>
            </div>

            <footer id="site-footer">
		<p><br><p>The Thomas A. Edison Papers is a project that narrates Edison's life and work through his documents.</p>
	  	<p>Federal funding provided by<br>
		<img id="neh-logo" src="https://edisondigital.rutgers.edu/files/asset/9f56a48869a5ff26ff889751bf7f5e7c7b4bb5fb.jpg" style="width:300px;border:10px solid white;border-radius:10px;margin-top:10px;"  alt="National Endowment for the Humanities">
	  	<br>																		
	  	<img id="nhprc-logo" src="https://edisondigital.rutgers.edu/files/asset/928a61ce131f35a19397840bbab6207e02b8b16e.png" alt="National Archives - National Historical Publications &amp; Records Commission" style="width:300px;border:10px solid white; border-radius:10px;">
	  	</p>																		

                <?php if ($footerContent = $this->themeSetting('footer')): ?>
                <?php echo $footerContent; ?>
                <?php else: ?>
                    <?php echo $this->translate('Powered by Omeka S'); ?>
                <?php endif; ?>

		<p>Copyright &copy; 2021 Rutgers, The State University of New Jersey, an equal opportunity, affirmative action institution. All rights reserved.</p>
		<p><br><p>
            </footer>


        </div>
    </body>
</html>
